script:
- echo "hello"
deploy:
  provider: heroku
  api_key:
    secure: yhVED0pjteLQwEa9ysQ3eEfBEd2D2UB2jzOhiy7UYKAZGZdTIMZfv3Zs1975r22GTmC9Tt3wMTSpePJMCbpaRYluKZafqxcxQz7Umcpo05B5RYldxdg1XwtWS4RdInELOxNQaWq6I0G9B9EGVxyvY6V+vt4GNtebWWOUTacdf7+DGzlgULqJeSAj40YkJexlZYAp8zjXrmQf8KapLmJvKlLWN2ulSdsX0/WyPjfiYV39ZA6SsMByFuvPzwTOwyGab26IisQtIMipts6WdTY+rF7Ufcv6gg6OS9XWbQAvXVhrJVoCLOFb5/3F83aTTqhHcEFysegfGqB85tL8chhLac4shqIPxz4BCd3U2/wCeBIntv1CMAiRtJ8Wq10Yj+cbSgaa8AAZQ576XRm1wMUegFqRZMugl+61VgfAJqDl0rVTpSkVf80Pndvnfo8pVjyYfVb4tcRWcfHesc+JJJrx8aVnIkONmybi+ADzg6h879Wu2YYF/QVhFppRz1uKD8dTIZ5oZztxSWko3Cf4PhmCVq3brdWKwvd4Xo5beoxz9hPCZ2pezUfCphkYljt/N11fES0ox2PajuU6KP9QEjWELIziLPoRcBRbdt6v4pGmCSwOLtToPR6/Aur0OCO8PwRXO8BUTaWOgL7tAaDzjRfeuKiIq3ILU4BWfImYoxH0fEY=
  app: pfebackend
