language: python
python:
- '3.7'
script:
- echo "hello"
deploy:
  provider: heroku
  api_key:
    secure: cyWAFCu2eNw8JqJ3ipznmjs15yTiK6pV8inoTJwopO0qnqkRv2CiDr+EAgBI5zlDtEI/Z3BElcPo3a5QwpP+zaYxOMFj8+Vb67G2slfcZZlbWwjpsjHfAmUNjjxnk2LoRrS/j/T2DO3bGM8Tfc4Eq/B1rbR90RZFgOpXhjLM4NqcM9skDg5qw7sK0ANB2XYpsrm+tUP9zsh92T8xpLwx5tQG16ZXdB8A/Xb0H2hUdTCj3CLvVM+nTsWqqkuRYtjxoZuk/FekMjwzYD2HGDgSUU6y9VH98nvVrmJlScNetCL6419rdvNbS73jK+vfQ7/WLvYJCOs8yp5u7zAiKXyV9sw6ADkfUbAwj4JOP4hwlvv3YCy+q571n/yjCWDeojCHVrkoO2pPm+NuQtRCwbNe21XGND+A3uJf9SAyTxyc4nNAQcfJ34HMlhUknjsEUjTm1a022eJo64T7J254g9YEDOxvnCCVpasTM/Qiayuto5l4dLzmHX4UJiuvZDSS9ox20IkB1IjqooEekTpysrcPfkiWwqjMFj6t7OE9mpU7zQBi3RlcCPuNe+P2F1RBF8mkiZ5hX29pwHZQP7Ykb8R1RGAoHrmSbvXqXKghZ/X5HRLkxLyHHapXLEl098xigxlygpYb6YQ+CnjRihBq+aAmhWJXSa0RdC4ONuFv0Sdvjwk=
