script:
- echo "hello"
deploy:
  provider: heroku
  api_key:
    secure: BzvGf3/rKTiifmnzys1BD7CSfENSPlNCMXCDMEjN/C6FoX8RGXYOLD3wk1NgRm/TgxSU3tyEQU4C2ba48bHSQm+snBJJIDmg1q0vrXYQhcElJ++NPVdVFqHKsnFmpfw8THDyvuX96o0hDZaLf3EUzdyrTL9htpJkvrfzFFd0Uxpg8SwQ/xn+uMLPAkg3oWuzr24cg6bwjWwZhZWg4efZ7cjGL9iS04UAkd5q+tU92HXvSIsxxlAUHYg2fliXt0shAVwz9YeMImgtIe6V5baATSXz7F2syAvU4SXN7jfd805qNcBsNur0o89K0FyZ0xCVHtU3FwSOTSnnbaB4DLz+hh/v4T5Ttn9Yfa4o7zC167gwiK8d2hxQ/lvBe4AQ4Y2ByeKbSQkZeQ7gHo3Ue/ocZgdBv95W9PfskbgCASQSjzrsEIqB9X462dOq0Ev3aG4hQPYmB7Kg8fIrwjALnyMsqmFFCyyKbecL2dhVmOo0WmfbqscbW+0hibN+xutWTLQAM97TPXvP9wBcnNScSUfT9abrcR0tG0VqURxypCnOXgYMTu+MZaOKsFBkpjpNF7tI6HVLx6zC6WKYsiJq12a5ieXOG2P+yGHcKralfOFc+HuogihNMakKTcxj7B4kpt6XD1sUPfUgGTQoIz/qgkDoDwZ+Uv4ii5j+ota/HibpLUA=
